### ISSUE TITLE
Wrong member IDs for relations, sometimes they are negative.

### ISSUE THREAD

**Issue by erictapen** [fosskers/streaming-osm#3]
I'm getting often wrong member IDs from parsing Openstreetmap Protobuf files.

```hs
import Control.Monad.Trans.Resource
import Streaming.Osm
import Streaming.Osm.Types
import Streaming.Prelude

main :: IO ()
main =
  let dataPath = "./test/diomede.osm.pbf"
   in do
        osmRelations <- runResourceT . toList_ . relations . blocks $ blobs dataPath
        Prelude.print $ _members $ Prelude.head osmRelations
```

```
[Member {_mref = 32973894, _mtype = W, _mrole = "outer"},Member {_mref = 4538375304, _mtype = N, _mrole = ""}]
```
`32973894` is right, but `4538375304` is definetely wrong when compared with [openstreetmap.org](https://www.openstreetmap.org/relation/6819495). In general about 50% of the wrong IDs appear to be negative. I sometimes see even unrealistically small IDs like `_mref = -9`.

To get sure that `diomede.osm.pbf` contains the correct information I used `osmium-tool` to verify that the second member ID of that relation should actually be `4571349198`:

```
$ osmium cat -f xml -o - ./test/diomede.osm.pbf
...
  <relation id="6819495" version="1" timestamp="2016-12-25T08:15:44Z" uid="1751737" user="Skybunny" changeset="44657363">
    <member type="way" ref="32973894" role="outer"/>
    <member type="node" ref="4571349198" role=""/>
...
```

**Comment by fosskers** [comment]
Is the `ref` the only field where you noticed an issue? Does all other data seem to be correct?

**Comment by fosskers** [comment]
I'm currently updating some dependencies, at which point we can make sure that `streaming-osm` is completely modern.

**Comment by erictapen** [comment]
> Is the `ref` the only field where you noticed an issue? Does all other data seem to be correct?

Yes, but I didn't look too much into other data.

**Comment by fosskers** [comment]
In that case I'll examine that bit of the parser directly.

**Comment by fosskers** [comment]
[I'm having trouble installing `osmium`](https://aur.archlinux.org/packages/osmium-tool/#comment-756024), so I'll have to trust your output for now and go from there.

**Comment by fosskers** [comment]
Testing on my own machine reveals:
```haskell
[Member {_mref = 32973894, _mtype = W, _mrole = "outer"},Member {_mref = 4538375304, _mtype = N, _mrole = ""}]
```
which is the exact result that you found, so we can rule out "well it works on my machine"-related issues.

**Comment by fosskers** [comment]
Here is where the member refs are parsed: https://github.com/fosskers/streaming-osm/blob/master/lib/Streaming/Osm/Internal/Parser.hs#L119

**Comment by fosskers** [comment]
```haskell
  ms <- map unzig . packed <$> (A.word8 0x4a *> varint >>= A.take) <|> pure []    -- memids
```
Okay, it's coming back to me.

- The `0x4a` marks the beginning of the specific section.
- The `varint` is how many of the following bytes belong to that section.
- `A.take` gathers that many bytes into a single `ByteString`.
- The `packed` breaks a `ByteString` into a group of "varints":
```haskell
-- | Reparse a `B.ByteString` as a list of some Varints.
packed :: B.ByteString -> [Int]
packed bs = either (const []) id $ A.parseOnly (A.many1' varint) bs
```
- And finally the `map unzig` decodes each `Int` from the "Z-encoding".
```haskell
-- | Decode a Z-encoded `Int`.
unzig :: Int -> Int
unzig n = shift n (-1) `xor` negate (n .&. 1)
```

**Comment by fosskers** [comment]
Can you do me a favour and run `osmium` over another file and find some other relation? I'd like to see what a relation with more than 2 members looks like, in terms of the `_mref`s.

**Comment by erictapen** [comment]
Thank you very much so far.

> Can you do me a favour and run `osmium` over another file and find some other relation? I'd like to see what a relation with more than 2 members looks like, in terms of the `_mref`s.

Sure!

```
$ osmium cat -f xml -o - ./test/ajishima.osm.pbf
...
  <relation id="1341344" version="4" timestamp="2017-01-21T07:02:37Z" uid="2480327" user="etajin" changeset="45344128">
    <member type="way" ref="179786323" role="outer"/>
    <member type="way" ref="131252919" role="outer"/>
    <member type="way" ref="131255782" role="outer"/>
    <member type="way" ref="131254179" role="outer"/>
    <member type="way" ref="131254769" role="outer"/>
    <member type="way" ref="131258500" role="outer"/>
    <member type="way" ref="131263564" role="outer"/>
    <member type="way" ref="179786324" role="outer"/>
    <member type="way" ref="131255746" role="outer"/>
    <member type="way" ref="131258720" role="outer"/>
    <member type="way" ref="131253237" role="outer"/>
    <member type="way" ref="131252889" role="outer"/>
    <member type="way" ref="91517011" role="inner"/>
    <member type="way" ref="91478320" role="inner"/>
    <member type="way" ref="91516694" role="inner"/>
    <member type="way" ref="91477474" role="inner"/>
    <member type="way" ref="91506694" role="inner"/>
    <member type="way" ref="91506952" role="inner"/>
    <member type="way" ref="91476273" role="inner"/>
    <tag k="natural" v="wood"/>
    <tag k="note" v="A13-06_04.xml"/>
    <tag k="source" v="MLIT, Japan"/>
    <tag k="source:ja" v="国土数値情報（森林地域データ）平成18年　国土交通省"/>
    <tag k="source_ref" v="http://nlftp.mlit.go.jp/ksj/jpgis/datalist/KsjTmplt-A13.html"/>
    <tag k="type" v="multipolygon"/>
  </relation>
...
```

> The problem then lies in how packed is parsing them, or in how unzig is decoding them.

I already had the suspicion that it had something to do with `unzig`, but I know too little about Protobuf and Haskell to work on it.

> I'm having trouble installing osmium, so I'll have to trust your output for now and go from there.

I can very much recommend to you the Nix package manager. With nix installed you can run `nix-shell -p osmium-tool` and get dropped into a shell with osmium available, without polluting your `PATH` permanently.

**Comment by fosskers** [comment]
Excellent. Tomorrow I'll test that particular relation to see if its member refs match what `osmium` has shown.

**Comment by fosskers** [comment]
The code can parse out the correct number of Members. Here are their values:
```
Member {_mref = 179786323, _mtype = W, _mrole = "outer"}
Member {_mref = -48533404, _mtype = W, _mrole = "outer"}
Member {_mref = 2863, _mtype = W, _mrole = "outer"}
Member {_mref = -1603, _mtype = W, _mrole = "outer"}
Member {_mref = 590, _mtype = W, _mrole = "outer"}
Member {_mref = 3731, _mtype = W, _mrole = "outer"}
Member {_mref = 5064, _mtype = W, _mrole = "outer"}
Member {_mref = 48522760, _mtype = W, _mrole = "outer"}
Member {_mref = -48530578, _mtype = W, _mrole = "outer"}
Member {_mref = 2974, _mtype = W, _mrole = "outer"}
Member {_mref = -5483, _mtype = W, _mrole = "outer"}
Member {_mref = -348, _mtype = W, _mrole = "outer"}
Member {_mref = -39735878, _mtype = W, _mrole = "inner"}
Member {_mref = -38691, _mtype = W, _mrole = "inner"}
Member {_mref = 38374, _mtype = W, _mrole = "inner"}
Member {_mref = -39220, _mtype = W, _mrole = "inner"}
Member {_mref = 29220, _mtype = W, _mrole = "inner"}
Member {_mref = 258, _mtype = W, _mrole = "inner"}
Member {_mref = -30679, _mtype = W, _mrole = "inner"}
```

**Comment by fosskers** [comment]
The tags seem to parse correctly as well. So the issue must indeed be within `unpacked` / `unzig`.

**Comment by erictapen** [comment]
Weird that the first value is parsed correctly, isn't it? Shouldn't the parser look at each binary segment independently without carrying state?

Btw could you give me a hint what [Z-encoding](https://github.com/fosskers/streaming-osm/blob/master/lib/Streaming/Osm/Internal/Util.hs#L90) is? I couldn't find anything about it.

**Comment by fosskers** [comment]
That's a good piece of evidence, I think. It makes me believe that `packed` is wrong.

Here's some more Z-encoding stuff in another package of mine: https://hackage.haskell.org/package/vectortiles-1.2.0.5/docs/Geography-VectorTile-Protobuf-Internal.html#g:3

Weird though... I can't find anything else about that while Googling, nor on https://wiki.openstreetmap.org/wiki/PBF_Format which I'm sure I referenced while writing the library originally.

**Comment by fosskers** [comment]
If I skip the unzigging entirely, I get totally different numbers:
```
Member {_mref = 359572646, _mtype = W, _mrole = "outer"}
Member {_mref = 97066807, _mtype = W, _mrole = "outer"}
Member {_mref = 5726, _mtype = W, _mrole = "outer"}
Member {_mref = 3205, _mtype = W, _mrole = "outer"}
Member {_mref = 1180, _mtype = W, _mrole = "outer"}
Member {_mref = 7462, _mtype = W, _mrole = "outer"}
Member {_mref = 10128, _mtype = W, _mrole = "outer"}
Member {_mref = 97045520, _mtype = W, _mrole = "outer"}
Member {_mref = 97061155, _mtype = W, _mrole = "outer"}
Member {_mref = 5948, _mtype = W, _mrole = "outer"}
Member {_mref = 10965, _mtype = W, _mrole = "outer"}
Member {_mref = 695, _mtype = W, _mrole = "outer"}
Member {_mref = 79471755, _mtype = W, _mrole = "inner"}
Member {_mref = 77381, _mtype = W, _mrole = "inner"}
Member {_mref = 76748, _mtype = W, _mrole = "inner"}
Member {_mref = 78439, _mtype = W, _mrole = "inner"}
Member {_mref = 58440, _mtype = W, _mrole = "inner"}
Member {_mref = 516, _mtype = W, _mrole = "inner"}
Member {_mref = 61357, _mtype = W, _mrole = "inner"}
```

**Comment by fosskers** [comment]
Oh.... https://github.com/fosskers/streaming-osm/blob/master/notes.org

**Comment by fosskers** [comment]
And yet `packed` seems to be working elsewhere...

**Comment by fosskers** [comment]
Oh thank god, it was low-hanging fruit. Turns out our offending line was the only place that `map unzig . packed` were used together, except for this:
```haskell
-- | Decode some packed, Z-encoded, delta-encoded Ints.
ints :: B.ByteString -> [Int]
ints = undelta . map unzig . packed
```
And sure enough, using `ints` on our bad line instead seems to solve the problem!

**Comment by fosskers** [comment]
[Done!](http://hackage.haskell.org/package/streaming-osm)

**Comment by erictapen** [comment]
Thank you so much! I justed tested it in my project and it works! Glad that I can remove the rust crate I had to write and go full Haskell as planned.

**Comment by fosskers** [comment]
Oh, hah, I'm sure the Rust version would be much faster. Yet rewriting a parser like this would be a pretty big pain.

**Comment by erictapen** [comment]
Ah I wasn't talking about writing a new osm parser in Rust. I was already using [osmpbfreader](https://crates.io/crates/osmpbfreader) and used it only to extract some data from a pbf file.

**Comment by fosskers** [comment]
Ah wonderful, so it already existed.
